"""
Default settings for the application.

These values serve as the production baseline. Override them via:
  1. Environment variables (highest priority)
  2. secrets/.env (deployed with the application)

Do not edit this file to change runtime behavior. Use env vars or
secrets/.env instead so that local development never leaks into
production and vice versa.
"""

from pathlib import Path

# ---------------------------------------------------------------------------
# Application environment
# ---------------------------------------------------------------------------
# One of: local, production. Drives any environment-specific behavior.
ENVIRONMENT = "production"

# ---------------------------------------------------------------------------
# Alpaca API
# ---------------------------------------------------------------------------
ALPACA_API_KEY = ""
ALPACA_API_SECRET = ""

# Paper trading vs live. Set to "https://api.alpaca.markets" for live.
ALPACA_BASE_URL = "https://paper-api.alpaca.markets"
ALPACA_DATA_URL = "https://data.alpaca.markets"

# ---------------------------------------------------------------------------
# Google Sheets
# ---------------------------------------------------------------------------
# Service-account JSON filename or absolute path.
GSHEET_ACCESS_KEY = "google-credentials.json"

# Spreadsheet ID (the long string in the sheet URL between /d/ and /edit).
GOOGLE_SHEET_ID = ""

# Default tab name for uploads.
GSHEET_TAB_NAME = "CSP"

# ---------------------------------------------------------------------------
# Default script parameters (can be overridden via CLI flags)
# ---------------------------------------------------------------------------
DEFAULT_SYMBOL = "TSLA"
DEFAULT_TARGET_DELTA = -0.18
DEFAULT_RESULT_COUNT = 4

# ---------------------------------------------------------------------------
# Cron / automation (check_market_and_upload.sh)
# ---------------------------------------------------------------------------
# Symbol used when the cron job runs without CLI arguments.
CRON_SYMBOL = "SPCX"
CRON_TARGET_DELTA = -0.18
CRON_COUNT = 4
CRON_USE_BOTH = True

# ---------------------------------------------------------------------------
# API / network tuning
# ---------------------------------------------------------------------------
# Rate-limit delay between Alpaca API calls (seconds).
API_DELAY = 0.15
# Max retries on 429 Too Many Requests.
API_MAX_RETRIES = 4
# Request timeout in seconds.
API_TIMEOUT = 30

# ---------------------------------------------------------------------------
# Paths (resolved at runtime relative to project root)
# ---------------------------------------------------------------------------
_PROJECT_ROOT = Path(__file__).resolve().parent.parent
SECRETS_DIR = _PROJECT_ROOT / "secrets"
LOG_FILE = _PROJECT_ROOT / "market_check.log"